// Generated by LiveScript 1.5.0
(function(){
  var fs, typedef, validator, validate, user;
  fs = require('fs');
  typedef = fs.readFileSync('./types/system.hs').toString('utf8');
  validator = require('./validator.js');
  validate = validator(typedef);
  user = {
    email: 'a.stegno@gmail.com',
    picture: 'http://some',
    firstname: 'Andrey',
    lastname: 'Test',
    status: 'active',
    bio: 'Ho',
    tags: ["user"]
  };
  console.log(validate("User", user));
}).call(this);
