// Generated by LiveScript 1.5.0
var fs, chai, expect, validator, typedef, validate;
fs = require('fs');
chai = require('chai');
expect = chai.expect;
validator = require('../lib/validator.js');
typedef = fs.readFileSync(__dirname + '/../examples/system.ft').toString('utf8');
validate = validator(typedef);
describe('UserModelCheck', function(){
  return it('Should Return True', function(){
    var user;
    user = {
      email: 'a.stegno@gmail.com',
      picture: 'http://some',
      firstname: 'Andrey',
      lastname: 'Test',
      status: 'active',
      bio: 'Ho',
      tags: ['user']
    };
    return expect(validate("User", user)).to.equal(true);
  });
});