// Generated by LiveScript 1.5.0
var fs, validator, typedef, validate, user;
fs = require('fs');
validator = require('../lib/validator.js');
typedef = fs.readFileSync(__dirname + '/../examples/system.ft').toString('utf8');
validate = validator(typedef);
user = {
  email: 'a.stegno@gmail.com',
  picture: 'http://some',
  firstname: 'Andrey',
  lastname: 'Test',
  status: 'active',
  bio: 'Ho',
  tags: ["user"]
};
console.log(validate("User", user));