// Generated by LiveScript 1.5.0
var fs, chai, expect, validator, validate;
fs = require('fs');
chai = require('chai');
expect = chai.expect;
validator = require('../lib/validator.js');
validate = validator({
  System: fs.readFileSync(__dirname + '/../examples/System.ft').toString('utf8'),
  Export: fs.readFileSync(__dirname + '/../examples/Export.ft').toString('utf8')
});
describe('Export', function(){
  it('Export Integer Test', function(){
    expect(validate("Export.Integer", 1)).to.equal(true);
    return expect(validate("Export.Integer", "1")).to.not.equal(true);
  });
  return it('Export String Test', function(){
    expect(validate("Export.String", "1")).to.equal(true);
    return expect(validate("Export.String", 1)).to.not.equal(true);
  });
});