// Generated by LiveScript 1.5.0
var fs, chai, expect, validator, validate;
fs = require('fs');
chai = require('chai');
expect = chai.expect;
validator = require('../lib/validator.js');
validate = validator({
  System: fs.readFileSync(__dirname + '/../examples/System.ft'),
  Export: fs.readFileSync(__dirname + '/../examples/Export.ft')
});
describe('Export', function(){
  it('Modules Test', function(){
    expect(validate.registry.System).to.have.property('String');
    return expect(validate.registry.Export).to.have.property('String');
  });
  it('Export Integer Test', function(){
    expect(validate("Export.Integer", 1)).to.equal(true);
    return expect(validate("Export.Integer", "1")).to.not.equal(true);
  });
  it('Export String Test', function(){
    expect(validate("Export.String", "1")).to.equal(true);
    return expect(validate("Export.String", 1)).to.not.equal(true);
  });
  return it('Wrapper Test', function(){
    var user, wrapper, wrongWrapper;
    user = {
      _id: (function(){
        _: return "Identity";
      }()),
      email: 'a.stegno@gmail.com',
      picture: 'http://some',
      firstname: 'Andrey',
      lastname: 'Jobs',
      status: 'active',
      bio: 'Ho',
      age: 19,
      tags: ['user', 'tag2']
    };
    wrapper = {
      user: user,
      key: "Some String",
      tags: ["user"]
    };
    expect(validate('Export.Wrapper', wrapper)).to.equal(true);
    wrongWrapper = {
      user: {
        wrong: "model"
      },
      key: "Some String",
      tags: ["user"]
    };
    return expect(validate('Export.Wrapper', wrongWrapper)).to.not.equal(true);
  });
});