// Generated by LiveScript 1.5.0
var fs, chai, expect, validator, validate;
fs = require('fs');
chai = require('chai');
expect = chai.expect;
validator = require('../lib/validator.js');
validate = validator({
  System: fs.readFileSync(__dirname + '/../examples/System.ft').toString('utf8')
});
describe('System', function(){
  it('Type Not Exists Test', function(){
    return expect(validate("TypeNotExists", "Some Custom String")).to.not.equal(true);
  });
  it('String Test', function(){
    expect(validate("System.String", "Some Custom String")).to.equal(true);
    return expect(validate("System.String", 1)).to.not.equal(true);
  });
  it('Integer Test', function(){
    expect(validate("System.Integer", 1)).to.equal(true);
    return expect(validate("System.Integer", "1")).to.not.equal(true);
  });
  it('Int Test', function(){
    expect(validate("System.Int", 10)).to.equal(true);
    return expect(validate("System.Int", null)).to.not.equal(true);
  });
  it('Double Test', function(){
    expect(validate("System.Double", 10.0)).to.equal(true);
    return expect(validate("System.Double", null)).to.not.equal(true);
  });
  it('Numeric Test', function(){
    expect(validate("System.Numeric", 10.0)).to.equal(true);
    return expect(validate("System.Numeric", "10.0")).to.not.equal(true);
  });
  it('Boolean Test (True)', function(){
    expect(validate("System.Boolean", true)).to.equal(true);
    expect(validate("System.Boolean", false)).to.equal(true);
    expect(validate("System.Bool", false)).to.equal(true);
    return expect(validate("System.Boolean", 5)).to.not.equal(true);
  });
  it('Null Test', function(){
    expect(validate("System.Null", null)).to.equal(true);
    return expect(validate("System.Null", "")).to.not.equal(true);
  });
  it('Undefined Test', function(){
    expect(validate("System.Undefined", undefined)).to.equal(true);
    expect(validate("System.Undefined", null)).to.not.equal(true);
    return expect(validate("System.Undefined", 1)).to.not.equal(true);
  });
  it('Email Test', function(){
    expect(validate("System.Email", "test@gmail.com")).to.equal(true);
    return expect(validate("System.Email", "test@gmail")).to.not.equal(true);
  });
  it('Status Test', function(){
    expect(validate("System.Status", "active")).to.equal(true);
    expect(validate("System.Status", "inactive")).to.equal(true);
    return expect(validate("System.Status", "invalid")).to.not.equal(true);
  });
  it('Missing Test', function(){
    expect(validate("System.Missing", undefined)).to.equal(true);
    expect(validate("System.Missing", null)).to.equal(true);
    return expect(validate("System.Missing", "invalid")).to.not.equal(true);
  });
  it('Array of String Test', function(){
    expect(validate("System.Strings", ["test"])).to.equal(true);
    expect(validate("System.Strings", ["test", "test"])).to.equal(true);
    expect(validate("System.Strings", "invalid")).to.not.equal(true);
    return expect(validate("System.Strings", ["test", "test", 1])).to.not.equal(true);
  });
  return it('Object Test', function(){
    var user;
    user = {
      email: 'a.stegno@gmail.com',
      picture: 'http://some',
      firstname: 'Andrey',
      lastname: 'Test',
      status: 'active',
      bio: 'Ho',
      tags: ['user']
    };
    return expect(validate("System.User", user)).to.equal(true);
  });
});